Rest api add download
amir1376/ab-download-manager pull request #331
Opened 2024-12-28 17:33 UTC by talha5389

Simple support for adding download via http api

2025-01-03 23:54 UTC, amir1376 requested changes
Hi. Thank you for your effort on this PR! I've added some comments to a few sections that I think they could be improved

2025-01-03 23:54 UTC, amir1376 commented on REST-API.md
Please improve this file.

2025-01-03 23:54 UTC, amir1376 commented on REST-API.md
> +To lazy to do it in openapi v3.
if its not possible for you to do this please remove this line for now.

2025-01-03 23:54 UTC, amir1376 commented on integration/server/src/main/kotlin/com/abdownloadmanager/integration/QueueModel.kt
> +data class QueueModel(
We already have QueueModel class in our code.
rename it to prevent conflicts.
for example `ApiQueueModel` , `QueueModelResponse`

2025-01-03 23:54 UTC, amir1376 commented on integration/server/src/main/kotlin/com/abdownloadmanager/integration/Integration.kt
> +            post("/add-download-task") {
there is already an `add` endpoint. (which is used for browser integration)
this name should be changed to prevent conflicts.
since you actually start a new download with all the configs requires for download you can  change it to something like `start-new-download`

2025-01-04 15:43 UTC, talha5389 commented
@amir1376 I have made requested changes.

2025-01-05 06:32 UTC, amir1376 approved these changes

2025-01-05 06:33 UTC, merged

2025-01-05 06:34 UTC, amir1376 commented
Thank you 🙏